/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/gke-labs/orchestra/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MultiKubernetesClusterBindingLister helps list MultiKubernetesClusterBindings.
// All objects returned here must be treated as read-only.
type MultiKubernetesClusterBindingLister interface {
	// List lists all MultiKubernetesClusterBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.MultiKubernetesClusterBinding, err error)
	// MultiKubernetesClusterBindings returns an object that can list and get MultiKubernetesClusterBindings.
	MultiKubernetesClusterBindings(namespace string) MultiKubernetesClusterBindingNamespaceLister
	MultiKubernetesClusterBindingListerExpansion
}

// multiKubernetesClusterBindingLister implements the MultiKubernetesClusterBindingLister interface.
type multiKubernetesClusterBindingLister struct {
	listers.ResourceIndexer[*apiv1alpha1.MultiKubernetesClusterBinding]
}

// NewMultiKubernetesClusterBindingLister returns a new MultiKubernetesClusterBindingLister.
func NewMultiKubernetesClusterBindingLister(indexer cache.Indexer) MultiKubernetesClusterBindingLister {
	return &multiKubernetesClusterBindingLister{listers.New[*apiv1alpha1.MultiKubernetesClusterBinding](indexer, apiv1alpha1.Resource("multikubernetesclusterbinding"))}
}

// MultiKubernetesClusterBindings returns an object that can list and get MultiKubernetesClusterBindings.
func (s *multiKubernetesClusterBindingLister) MultiKubernetesClusterBindings(namespace string) MultiKubernetesClusterBindingNamespaceLister {
	return multiKubernetesClusterBindingNamespaceLister{listers.NewNamespaced[*apiv1alpha1.MultiKubernetesClusterBinding](s.ResourceIndexer, namespace)}
}

// MultiKubernetesClusterBindingNamespaceLister helps list and get MultiKubernetesClusterBindings.
// All objects returned here must be treated as read-only.
type MultiKubernetesClusterBindingNamespaceLister interface {
	// List lists all MultiKubernetesClusterBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.MultiKubernetesClusterBinding, err error)
	// Get retrieves the MultiKubernetesClusterBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.MultiKubernetesClusterBinding, error)
	MultiKubernetesClusterBindingNamespaceListerExpansion
}

// multiKubernetesClusterBindingNamespaceLister implements the MultiKubernetesClusterBindingNamespaceLister
// interface.
type multiKubernetesClusterBindingNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.MultiKubernetesClusterBinding]
}
