/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/gke-labs/orchestra/api/v1alpha1"
	scheme "github.com/gke-labs/orchestra/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MultiKubernetesClusterBindingsGetter has a method to return a MultiKubernetesClusterBindingInterface.
// A group's client should implement this interface.
type MultiKubernetesClusterBindingsGetter interface {
	MultiKubernetesClusterBindings(namespace string) MultiKubernetesClusterBindingInterface
}

// MultiKubernetesClusterBindingInterface has methods to work with MultiKubernetesClusterBinding resources.
type MultiKubernetesClusterBindingInterface interface {
	Create(ctx context.Context, multiKubernetesClusterBinding *apiv1alpha1.MultiKubernetesClusterBinding, opts v1.CreateOptions) (*apiv1alpha1.MultiKubernetesClusterBinding, error)
	Update(ctx context.Context, multiKubernetesClusterBinding *apiv1alpha1.MultiKubernetesClusterBinding, opts v1.UpdateOptions) (*apiv1alpha1.MultiKubernetesClusterBinding, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, multiKubernetesClusterBinding *apiv1alpha1.MultiKubernetesClusterBinding, opts v1.UpdateOptions) (*apiv1alpha1.MultiKubernetesClusterBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.MultiKubernetesClusterBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.MultiKubernetesClusterBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.MultiKubernetesClusterBinding, err error)
	MultiKubernetesClusterBindingExpansion
}

// multiKubernetesClusterBindings implements MultiKubernetesClusterBindingInterface
type multiKubernetesClusterBindings struct {
	*gentype.ClientWithList[*apiv1alpha1.MultiKubernetesClusterBinding, *apiv1alpha1.MultiKubernetesClusterBindingList]
}

// newMultiKubernetesClusterBindings returns a MultiKubernetesClusterBindings
func newMultiKubernetesClusterBindings(c *ApiV1alpha1Client, namespace string) *multiKubernetesClusterBindings {
	return &multiKubernetesClusterBindings{
		gentype.NewClientWithList[*apiv1alpha1.MultiKubernetesClusterBinding, *apiv1alpha1.MultiKubernetesClusterBindingList](
			"multikubernetesclusterbindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.MultiKubernetesClusterBinding { return &apiv1alpha1.MultiKubernetesClusterBinding{} },
			func() *apiv1alpha1.MultiKubernetesClusterBindingList {
				return &apiv1alpha1.MultiKubernetesClusterBindingList{}
			},
		),
	}
}
