/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/gke-labs/orchestra/api/v1alpha1"
	scheme "github.com/gke-labs/orchestra/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MultiKubernetesClusterPlacementsGetter has a method to return a MultiKubernetesClusterPlacementInterface.
// A group's client should implement this interface.
type MultiKubernetesClusterPlacementsGetter interface {
	MultiKubernetesClusterPlacements(namespace string) MultiKubernetesClusterPlacementInterface
}

// MultiKubernetesClusterPlacementInterface has methods to work with MultiKubernetesClusterPlacement resources.
type MultiKubernetesClusterPlacementInterface interface {
	Create(ctx context.Context, multiKubernetesClusterPlacement *apiv1alpha1.MultiKubernetesClusterPlacement, opts v1.CreateOptions) (*apiv1alpha1.MultiKubernetesClusterPlacement, error)
	Update(ctx context.Context, multiKubernetesClusterPlacement *apiv1alpha1.MultiKubernetesClusterPlacement, opts v1.UpdateOptions) (*apiv1alpha1.MultiKubernetesClusterPlacement, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, multiKubernetesClusterPlacement *apiv1alpha1.MultiKubernetesClusterPlacement, opts v1.UpdateOptions) (*apiv1alpha1.MultiKubernetesClusterPlacement, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.MultiKubernetesClusterPlacement, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.MultiKubernetesClusterPlacementList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.MultiKubernetesClusterPlacement, err error)
	MultiKubernetesClusterPlacementExpansion
}

// multiKubernetesClusterPlacements implements MultiKubernetesClusterPlacementInterface
type multiKubernetesClusterPlacements struct {
	*gentype.ClientWithList[*apiv1alpha1.MultiKubernetesClusterPlacement, *apiv1alpha1.MultiKubernetesClusterPlacementList]
}

// newMultiKubernetesClusterPlacements returns a MultiKubernetesClusterPlacements
func newMultiKubernetesClusterPlacements(c *ApiV1alpha1Client, namespace string) *multiKubernetesClusterPlacements {
	return &multiKubernetesClusterPlacements{
		gentype.NewClientWithList[*apiv1alpha1.MultiKubernetesClusterPlacement, *apiv1alpha1.MultiKubernetesClusterPlacementList](
			"multikubernetesclusterplacements",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.MultiKubernetesClusterPlacement {
				return &apiv1alpha1.MultiKubernetesClusterPlacement{}
			},
			func() *apiv1alpha1.MultiKubernetesClusterPlacementList {
				return &apiv1alpha1.MultiKubernetesClusterPlacementList{}
			},
		),
	}
}
