apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: orchestra
    app.kubernetes.io/managed-by: kustomize
  name: orchestra-controller-manager-metrics-service
  namespace: orchestra-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager
