//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscaleForCapacity) DeepCopyInto(out *AutoscaleForCapacity) {
	*out = *in
	if in.WorkloadDetails != nil {
		in, out := &in.WorkloadDetails, &out.WorkloadDetails
		*out = new(WorkloadDetails)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscaleForCapacity.
func (in *AutoscaleForCapacity) DeepCopy() *AutoscaleForCapacity {
	if in == nil {
		return nil
	}
	out := new(AutoscaleForCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupVersionKind) DeepCopyInto(out *GroupVersionKind) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupVersionKind.
func (in *GroupVersionKind) DeepCopy() *GroupVersionKind {
	if in == nil {
		return nil
	}
	out := new(GroupVersionKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiKubernetesClusterBinding) DeepCopyInto(out *MultiKubernetesClusterBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiKubernetesClusterBinding.
func (in *MultiKubernetesClusterBinding) DeepCopy() *MultiKubernetesClusterBinding {
	if in == nil {
		return nil
	}
	out := new(MultiKubernetesClusterBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiKubernetesClusterBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiKubernetesClusterBindingList) DeepCopyInto(out *MultiKubernetesClusterBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MultiKubernetesClusterBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiKubernetesClusterBindingList.
func (in *MultiKubernetesClusterBindingList) DeepCopy() *MultiKubernetesClusterBindingList {
	if in == nil {
		return nil
	}
	out := new(MultiKubernetesClusterBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiKubernetesClusterBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiKubernetesClusterBindingSpec) DeepCopyInto(out *MultiKubernetesClusterBindingSpec) {
	*out = *in
	out.SourceRef = in.SourceRef
	out.PlacementRef = in.PlacementRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiKubernetesClusterBindingSpec.
func (in *MultiKubernetesClusterBindingSpec) DeepCopy() *MultiKubernetesClusterBindingSpec {
	if in == nil {
		return nil
	}
	out := new(MultiKubernetesClusterBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiKubernetesClusterBindingStatus) DeepCopyInto(out *MultiKubernetesClusterBindingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiKubernetesClusterBindingStatus.
func (in *MultiKubernetesClusterBindingStatus) DeepCopy() *MultiKubernetesClusterBindingStatus {
	if in == nil {
		return nil
	}
	out := new(MultiKubernetesClusterBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiKubernetesClusterPlacement) DeepCopyInto(out *MultiKubernetesClusterPlacement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiKubernetesClusterPlacement.
func (in *MultiKubernetesClusterPlacement) DeepCopy() *MultiKubernetesClusterPlacement {
	if in == nil {
		return nil
	}
	out := new(MultiKubernetesClusterPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiKubernetesClusterPlacement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiKubernetesClusterPlacementList) DeepCopyInto(out *MultiKubernetesClusterPlacementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MultiKubernetesClusterPlacement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiKubernetesClusterPlacementList.
func (in *MultiKubernetesClusterPlacementList) DeepCopy() *MultiKubernetesClusterPlacementList {
	if in == nil {
		return nil
	}
	out := new(MultiKubernetesClusterPlacementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiKubernetesClusterPlacementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiKubernetesClusterPlacementSpec) DeepCopyInto(out *MultiKubernetesClusterPlacementSpec) {
	*out = *in
	if in.ClusterSelectorRules != nil {
		in, out := &in.ClusterSelectorRules, &out.ClusterSelectorRules
		*out = make([]PlacementClusterSelectorRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Scaling.DeepCopyInto(&out.Scaling)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiKubernetesClusterPlacementSpec.
func (in *MultiKubernetesClusterPlacementSpec) DeepCopy() *MultiKubernetesClusterPlacementSpec {
	if in == nil {
		return nil
	}
	out := new(MultiKubernetesClusterPlacementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiKubernetesClusterPlacementStatus) DeepCopyInto(out *MultiKubernetesClusterPlacementStatus) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]PlacementCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastAdditionTime.DeepCopyInto(&out.LastAdditionTime)
	in.LastClusterRemovalTime.DeepCopyInto(&out.LastClusterRemovalTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiKubernetesClusterPlacementStatus.
func (in *MultiKubernetesClusterPlacementStatus) DeepCopy() *MultiKubernetesClusterPlacementStatus {
	if in == nil {
		return nil
	}
	out := new(MultiKubernetesClusterPlacementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementCluster) DeepCopyInto(out *PlacementCluster) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	if in.AtCapacityCeiling != nil {
		in, out := &in.AtCapacityCeiling, &out.AtCapacityCeiling
		*out = new(bool)
		**out = **in
	}
	if in.Draining != nil {
		in, out := &in.Draining, &out.Draining
		*out = new(PlacementClusterDraining)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementCluster.
func (in *PlacementCluster) DeepCopy() *PlacementCluster {
	if in == nil {
		return nil
	}
	out := new(PlacementCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementClusterDraining) DeepCopyInto(out *PlacementClusterDraining) {
	*out = *in
	in.LastReplicaCountDecrease.DeepCopyInto(&out.LastReplicaCountDecrease)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementClusterDraining.
func (in *PlacementClusterDraining) DeepCopy() *PlacementClusterDraining {
	if in == nil {
		return nil
	}
	out := new(PlacementClusterDraining)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementClusterSelectorRule) DeepCopyInto(out *PlacementClusterSelectorRule) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementClusterSelectorRule.
func (in *PlacementClusterSelectorRule) DeepCopy() *PlacementClusterSelectorRule {
	if in == nil {
		return nil
	}
	out := new(PlacementClusterSelectorRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementRef) DeepCopyInto(out *PlacementRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementRef.
func (in *PlacementRef) DeepCopy() *PlacementRef {
	if in == nil {
		return nil
	}
	out := new(PlacementRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Scaling) DeepCopyInto(out *Scaling) {
	*out = *in
	if in.AutoscaleForCapacity != nil {
		in, out := &in.AutoscaleForCapacity, &out.AutoscaleForCapacity
		*out = new(AutoscaleForCapacity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Scaling.
func (in *Scaling) DeepCopy() *Scaling {
	if in == nil {
		return nil
	}
	out := new(Scaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceRef) DeepCopyInto(out *SourceRef) {
	*out = *in
	out.GroupVersionKind = in.GroupVersionKind
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceRef.
func (in *SourceRef) DeepCopy() *SourceRef {
	if in == nil {
		return nil
	}
	out := new(SourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadDetails) DeepCopyInto(out *WorkloadDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadDetails.
func (in *WorkloadDetails) DeepCopy() *WorkloadDetails {
	if in == nil {
		return nil
	}
	out := new(WorkloadDetails)
	in.DeepCopyInto(out)
	return out
}
