/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	orchestraapiv1alpha1 "github.com/gke-labs/orchestra/api/v1alpha1"
	versioned "github.com/gke-labs/orchestra/pkg/client/clientset/versioned"
	internalinterfaces "github.com/gke-labs/orchestra/pkg/client/informers/externalversions/internalinterfaces"
	apiv1alpha1 "github.com/gke-labs/orchestra/pkg/client/listers/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MultiKubernetesClusterBindingInformer provides access to a shared informer and lister for
// MultiKubernetesClusterBindings.
type MultiKubernetesClusterBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1alpha1.MultiKubernetesClusterBindingLister
}

type multiKubernetesClusterBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMultiKubernetesClusterBindingInformer constructs a new informer for MultiKubernetesClusterBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMultiKubernetesClusterBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMultiKubernetesClusterBindingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMultiKubernetesClusterBindingInformer constructs a new informer for MultiKubernetesClusterBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMultiKubernetesClusterBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().MultiKubernetesClusterBindings(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().MultiKubernetesClusterBindings(namespace).Watch(context.TODO(), options)
			},
		},
		&orchestraapiv1alpha1.MultiKubernetesClusterBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *multiKubernetesClusterBindingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMultiKubernetesClusterBindingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *multiKubernetesClusterBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&orchestraapiv1alpha1.MultiKubernetesClusterBinding{}, f.defaultInformer)
}

func (f *multiKubernetesClusterBindingInformer) Lister() apiv1alpha1.MultiKubernetesClusterBindingLister {
	return apiv1alpha1.NewMultiKubernetesClusterBindingLister(f.Informer().GetIndexer())
}
